### ISSUE TITLE
可以发下sql吗 大佬

### ISSUE THREAD

**Issue by c55403225** [xoxosos/vue-ace-admin#2]
可以发下sql吗 大佬

**Comment by c55403225** [comment]
能留个联系方式嘛

**Comment by xoxosos** [comment]
> 能留个联系方式嘛

你可以添加我的qq: 1530508034

**Comment by xoxosos** [comment]
> 可以发下sql吗 大佬

后面会考虑开放Java的代码

**Comment by c55403225** [comment]
大佬加一下我55403225,你的找不到
![image](https://github.com/xoxosos/vue-ace-admin/assets/58025606/9f7c2856-8c8c-4933-ab26-c4d8e8374514)

**Comment by Ozzie57** [comment]
我也要加下。。。
