### ISSUE TITLE
路由切换会导致页面空白

### ISSUE THREAD

**Issue by c55403225** [xoxosos/vue-ace-admin#6]
路由切换会导致页面空白
![image](https://github.com/xoxosos/vue-ace-admin/assets/58025606/a95cf76c-6f45-422c-817d-5f8bd2c91f1e)
还有警告的问题
![image](https://github.com/xoxosos/vue-ace-admin/assets/58025606/548a86b3-4102-420f-9d43-7d15af79a007)

**Comment by xoxosos** [comment]
这个应该跟默认组件导入的模式有关 我看下

**Comment by c55403225** [comment]
好的 大佬

**Comment by xoxosos** [comment]
> 好的 大佬

吃完饭看看

**Comment by c55403225** [comment]
ok

**Comment by xoxosos** [comment]
处理好了

**Comment by c55403225** [comment]
好的

**Comment by c55403225** [comment]
强
